export const icons = {
  arrowDown: require("@/assets/icons/arrow-down.png"),
  arrowUp: require("@/assets/icons/arrow-up.png"),
  backArrow: require("@/assets/icons/back-arrow.png"),
  chat: require("@/assets/icons/chat.png"),
  checkmark: require("@/assets/icons/check.png"),
  close: require("@/assets/icons/close.png"),
  dollar: require("@/assets/icons/dollar.png"),
  email: require("@/assets/icons/email.png"),
  eyecross: require("@/assets/icons/eyecross.png"),
  google: require("@/assets/icons/google.png"),
  home: require("@/assets/icons/home.png"),
  list: require("@/assets/icons/list.png"),
  lock: require("@/assets/icons/lock.png"),
  map: require("@/assets/icons/map.png"),
  marker: require("@/assets/icons/marker.png"),
  out: require("@/assets/icons/out.png"),
  person: require("@/assets/icons/person.png"),
  pin: require("@/assets/icons/pin.png"),
  point: require("@/assets/icons/point.png"),
  profile: require("@/assets/icons/profile.png"),
  search: require("@/assets/icons/search.png"),
  selectedMarker: require("@/assets/icons/selected-marker.png"),
  star: require("@/assets/icons/star.png"),
  target: require("@/assets/icons/target.png"),
  to: require("@/assets/icons/to.png"),
};
